### ISSUE TITLE
cannot build a release on Apple Silicon (Mac M3 Pro)

### ISSUE THREAD

**Issue by pietroppeter** [nim-lang/choosenim#9] opened 2024-07-21 16:43 UTC
I tried building (with `nimble release`) on a Mac M3 Pro and it errors out. Seeing the state of the original fork this is not unexpected (see e.g. https://github.com/dom96/choosenim/pull/301). Adding the error I get below.

I am not sure what is the current state of this fork, would be happy to help and try test fixes if there are some ready.

I noticed also choosenim depends on a fixed nimble commit.

## error message

```
➜  choosenim git:(v0.8.4) ✗ nimble release
  Verifying dependencies for choosenim@0.8.4
     Info:  Dependency on nimble@#8f7af86 already satisfied
  Verifying dependencies for nimble@0.12.0
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on analytics@>= 0.3.0 already satisfied
  Verifying dependencies for analytics@0.3.0
     Info:  Dependency on uuids@>= 0.1.7 already satisfied
  Verifying dependencies for uuids@0.1.12
     Info:  Dependency on isaac@>= 0.1.3 already satisfied
  Verifying dependencies for isaac@0.1.3
     Info:  Dependency on osinfo@>= 0.3.0 already satisfied
  Verifying dependencies for osinfo@0.3.2
     Info:  Dependency on puppy@>= 1.2.1 already satisfied
  Verifying dependencies for puppy@2.1.2
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on zippy@>= 0.10.0 already satisfied
  Verifying dependencies for zippy@0.10.14
     Info:  Dependency on webby@>= 0.2.0 already satisfied
  Verifying dependencies for webby@0.2.1
     Info:  Dependency on osinfo@>= 0.3.0 already satisfied
  Verifying dependencies for osinfo@0.3.2
     Info:  Dependency on zippy@>= 0.7.2 already satisfied
  Verifying dependencies for zippy@0.10.14
  Executing task release in /Users/pietropeterlongo/recursing/choosenim/choosenim.nimble
  Verifying dependencies for choosenim@0.8.4
     Info:  Dependency on nimble@#8f7af86 already satisfied
  Verifying dependencies for nimble@0.12.0
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on analytics@>= 0.3.0 already satisfied
  Verifying dependencies for analytics@0.3.0
     Info:  Dependency on uuids@>= 0.1.7 already satisfied
  Verifying dependencies for uuids@0.1.12
     Info:  Dependency on isaac@>= 0.1.3 already satisfied
  Verifying dependencies for isaac@0.1.3
     Info:  Dependency on osinfo@>= 0.3.0 already satisfied
  Verifying dependencies for osinfo@0.3.2
     Info:  Dependency on puppy@>= 1.2.1 already satisfied
  Verifying dependencies for puppy@2.1.2
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on zippy@>= 0.10.0 already satisfied
  Verifying dependencies for zippy@0.10.14
     Info:  Dependency on webby@>= 0.2.0 already satisfied
  Verifying dependencies for webby@0.2.1
     Info:  Dependency on osinfo@>= 0.3.0 already satisfied
  Verifying dependencies for osinfo@0.3.2
     Info:  Dependency on zippy@>= 0.7.2 already satisfied
  Verifying dependencies for zippy@0.10.14
   Building choosenim/choosenim using c backend
/Users/pietropeterlongo/.nimble/pkgs2/nimble-0.12.0-7aa4f8f5d3b79013b9aa93f3069f4eaaebd24a48/nimblepkg/options.nim(165, 14) Warning: Couldn't determine GIT hash: fatal: not a git repository (or any of the parent directories): .git [User]
/Users/pietropeterlongo/recursing/choosenim/src/choosenimpkg/download.nim(72, 26) Warning: See corresponding Defect; AssertionError is deprecated [Deprecated]
/Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@sobjc.nim.c:77:10: error: incompatible function pointer types assigning to 'tyProc__ELDcQK9cgdUyzj5KMs6i3sA' (aka 'long long (*)(long long, long long)') from 'tyProc__ln4kdL5W9bbX4a1xl8nnVXQ' (aka 'void (*)(void)') [-Wincompatible-function-pointer-types]
        msgSend = Dl_3741319184_;
                ^ ~~~~~~~~~~~~~~
/Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@sobjc.nim.c:129:10: error: incompatible function pointer types assigning to 'tyProc__GzHItWOV8mXMIORHhW0e0Q' (aka 'long long (*)(long long, long long, char *)') from 'tyProc__ln4kdL5W9bbX4a1xl8nnVXQ' (aka 'void (*)(void)') [-Wincompatible-function-pointer-types]
        msgSend = Dl_3741319184_;
                ^ ~~~~~~~~~~~~~~
/Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@sobjc.nim.c:145:10: error: incompatible function pointer types assigning to 'tyProc__RgKKSNSZBwbKmv4OT9c1inQ' (aka 'char *(*)(long long, long long)') from 'tyProc__ln4kdL5W9bbX4a1xl8nnVXQ' (aka 'void (*)(void)') [-Wincompatible-function-pointer-types]
        msgSend = Dl_3741319184_;
                ^ ~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 errors generated.
/Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@splatform.nim.c:208:10: error: incompatible function pointer types assigning to 'tyProc__I9bK10SEvRG6xAbMkITEqZA' (aka 'long long (*)(long long, long long, long long, long long, double)') from 'tyProc__ln4kdL5W9bbX4a1xl8nnVXQ' (aka 'void (*)(void)') [-Wincompatible-function-pointer-types]
        msgSend = Dl_3741319184_;
                ^ ~~~~~~~~~~~~~~
/Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@splatform.nim.c:219:10: error: incompatible function pointer types assigning to 'tyProc__DB8G6BUgjI9c1JzPVrFJpUg' (aka 'long long (*)(long long, long long, long long)') from 'tyProc__ln4kdL5W9bbX4a1xl8nnVXQ' (aka 'void (*)(void)') [-Wincompatible-function-pointer-types]
        msgSend = Dl_3741319184_;
                ^ ~~~~~~~~~~~~~~
/Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@splatform.nim.c:229:10: error: incompatible function pointer types assigning to 'tyProc__mV9cvtvcTvdBpTeuL8riRFQ' (aka 'void (*)(long long, long long, long long)') from 'tyProc__ln4kdL5W9bbX4a1xl8nnVXQ' (aka 'void (*)(void)') [-Wincompatible-function-pointer-types]
        msgSend = Dl_3741319184_;
                ^ ~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
Error: execution of an external compiler program 'clang -c  -w -ferror-limit=3 -pthread -O3   -I/Users/pietropeterlongo/recursing/Nim/lib -I/Users/pietropeterlongo/recursing/choosenim/src -o /Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@sobjc.nim.c.o /Users/pietropeterlongo/.cache/nim/choosenim_r/@m..@s..@s..@s.nimble@spkgs2@spuppy-2.1.2-9d583654c5ce17fd0223da5102e5e9b01fba74fa@spuppy@splatforms@smacos@sobjc.nim.c' failed with exit code: 1


4 errors generated.
       Tip: 26 messages have been suppressed, use --verbose to show them.
nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: choosenim
stack trace: (most recent call last)
/private/var/folders/tj/11x919296w32rbj015qwdl4c0000gn/T/nimblecache-1314761008/nimscriptapi_3146622833.nim(212, 16)
/Users/pietropeterlongo/recursing/choosenim/choosenim.nimble(27, 3) releaseTask
/Users/pietropeterlongo/recursing/Nim/lib/system/nimscript.nim(265, 7) exec
/Users/pietropeterlongo/recursing/Nim/lib/system/nimscript.nim(265, 7) Error: unhandled exception: FAILED: nimble build -d:release [OSError]
       Tip: 26 messages have been suppressed, use --verbose to show them.
nimscriptwrapper.nim(161) execScript

    Error:  Exception raised during nimble script execution
```

## details

`nim -v` (Nim built from sources):
```
Nim Compiler Version 2.0.8 [MacOSX: arm64]
Compiled at 2024-07-21
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
```

`nimble -v`:
```
nimble v0.14.2 compiled at 2024-07-21 16:13:07
git hash: be2f1309b35a6189ff5eb34a007793e6d3f94157
```

**Comment by ringabout** [comment] 2024-08-29 09:20
I suppose it was fixed by https://github.com/nim-lang/choosenim/pull/10

**Comment by ringabout** [comment] 2024-08-29 09:21
for the record, the root cause is https://github.com/treeform/puppy/issues/118

**Closed by ringabout** 2024-08-29 09:20 UTC
